### ISSUE TITLE
Undo fork

### ISSUE THREAD

**Issue by CallumJHays** [annotationhub/react-golden-layout#4]
It appears this project is a complete fork of the original [Golden Layout project](https://github.com/golden-layout/golden-layout) with react functionality tacked on. I think it would be easier to maintain this down the line if we specified upstream golden layout as an npm dependency and simply added react functionality downstream in this repo. This is particularly important in my thinking as the golden layout devs are working on v2.0 (releasing soon)

**Comment by lsimkins** [comment]
Thanks for the suggestion. We thought about forking vs upstream dependency and decided to fork to maintain our own version of the library for a project we're doing. I haven't seen any movement on the original library for the past few months, so I went with the assumption that GL 2.0 is sidelined. 

We primarily forked to give us the ability to maintain & improve the core library as needed.

If we see movement on the core library we'll reverse the decision & make GL an upstream dep.
